namespace Domain.Enums
{
    public enum MedicalSpecialistType
    {
        Allergists,
        Anesthesiologists,
        Cardiologists,
        Dermatologists,
        Endocrinologists,
        Gastroenterologists,
        Internists,
        Nephrologists,
        Neurologists,
        Obstetricians,
        Oncologists,
        Ophthalmologists,
        Osteopaths,
        Otolaryngologists,
        Pathologists,
        Pediatricians,
        Physiatrists,
        Podiatrists,
        Psychiatrists,
        Pulmonologists,
        Radiologists,
        Rheumatologists,
        Urologists
    }
}
